### ISSUE TITLE
Use forked version of GenX

### ISSUE THREAD

**Issue by RuaridhMacd** [macroenergy/DOLPHYN#120]
We’re currently using an older, frozen, version of GenX in Dolphyn. This means we’re not benefitting from updates being made to GenX and there’s increasing amounts of duplication of work.

To resolve this, I’ll add a forked version of GenX as a submodule.

This issue relates to getting a minimum working version of this. It’ll rely on some hardcoded patching between the two. We have started an effort to rewrite GenX and Dolphyn to work together better and be more extensible to other sectors.

**Comment by RuaridhMacd** [comment]
- [ ] Replace existing version of GenX with submodule
- [ ] Change "include" imports to point to submodule
- [ ] Create interfacing functions to add elements to GenX in DOLPHYN. This will make future changes easier
- [ ] Apply interface functions everywhere
- [ ] Test on the GenX and DOLPHYN example systems and fix bugs

**Comment by RuaridhMacd** [comment]
Right now the branch works for me. Some of the results are different from the examples / benchmarks, do more work is needed to see why there are differences.

@Betristor , it would be great if you could trial the code when you have time.

git / Github sometimes has trouble setting up a branch with a submodule when the main branch doesn't also include that submodule. Let me know if you have any issues.

**Comment by Betristor** [comment]
Ok, Mac. I should test the code in a week after the spring festival.

**Comment by RuaridhMacd** [comment]
Thanks very much.

**Comment by RuaridhMacd** [comment]
- [ ] Add brief instructions for how to download a submodule
- [ ] Add a comment which lists the changes in inputs and settings

**Comment by RuaridhMacd** [comment]
Closing to clean up our issues list. This will become a new PR at the next meeting.
