### ISSUE TITLE
Liquefaction documentation

### ISSUE THREAD

**Issue by dharik13** [macroenergy/DOLPHYN#121]
Need to add documentation to describe new features related to liquefaction modeling

**Comment by RuaridhMacd** [comment]
@Betristor @anna-nadia @dharik13 

We need to revise the H2 documentation for clarity and to re-organize the indexes. We need to decide whether different resources need different indexes vs the same one.

For now, we're proposed to revise the indices to be :
- g \in G : all hydrogen generators
- k \in K , where K \sub G : liquefaction resources

- [ ] @anna-nadia will propose an indexing rule and we can review next meeting.

**Comment by Betristor** [comment]
@anna-nadia I think it's necessary to distinguish the liquefaction plant with other plants like SMR if you regard them as a unique type generator.
From the viewpoint of regarding liquefaction as generators (in code), the production plant and compressor are bundled to be a single part, making it reseaonable to denote them with index g or k; but from the viewpoint of physical facts, liquefaction consumes electricity and gas hydrogen to make liquid hydrogen, where the essential part lies at the compressor. In balance a term $x_{t,z}^{Compressed}$ could be subtracted to fulfill it. With loss consideration, liquid hydrogen could be calculated based on this term, so is consumption of electricity.

**Comment by RuaridhMacd** [comment]
Resolved by PR #114
