### ISSUE TITLE
package activation errors

### ISSUE THREAD

**Issue by nxshi** [macroenergy/DOLPHYN#124]
- problems activating julenv.jl and Project.toml when setting up on new local devices: specifically on Mac M1 Max (needs Julia 1.8.5)
- process should also be streamlined so it is easily configurable on multiple devices

**Comment by RuaridhMacd** [comment]
- [ ] Complete port of GenX approach to DOLPHYN @RuaridhMacd

**Comment by RuaridhMacd** [comment]
Resolved in PR #144
