### ISSUE TITLE
PR #115 may have reintroduced old code

### ISSUE THREAD

**Issue by RuaridhMacd** [macroenergy/DOLPHYN#143]
Hi @gn-he and @Betristor 

PR #115 may have accidentally reintroduced some old code when you were merging it with main.

I was working with h2_truck_all and there are a mix of constraints using zones and routes. I think the zone-based indexing was reintroduced in this commit: "[Merge branch 'main' into truck_route_index](https://github.com/macroenergy/DOLPHYN/pull/115/commits/93ad4508fd6267e320f5be749d3444719f2395dd)"

Could you check if the code should be removed and push a PR with the fixes?

Thanks

**Comment by RuaridhMacd** [comment]
@Betristor I think I have resolved the issues in the code. One problem I've identified in the ThreeZone example is that setting Zones = ["z1", "z2", "z3"] will lead to an unsolvable model. Zones = [1, 2, 3] works but I believe there are some errors.

The zones in the inputs must exactly the Zones setting / input for the filter() function to correctly reduce the inputs, but then I'm not sure all the other data is being handled correctly.

I will continue to look into it

**Comment by Betristor** [comment]
@RuaridhMacd thanks for efforts in solving the mistake introduced by PR #115, it was developed before main branch was updated so some old codes are kept. I intend to reintroduce some features like zone selection and outputs redirecting based on your PR #144.

**Comment by Betristor** [comment]
@RuaridhMacd I'll rewrite the truck module in next week after this hackthon based on main branch. And I may consider keeping original truck modeling index way for current users to have adoption. And since your branch has fixed the problems, I shall close this issue, may I?

**Comment by RuaridhMacd** [comment]
Resolved in PR #144 
Some elements of the Zones code have not been re-instated
