### ISSUE TITLE
Automatically test examples for new PRs

### ISSUE THREAD

**Issue by RuaridhMacd** [macroenergy/DOLPHYN#152]
@Betristor 
- [x] Create a workflow in GitHub Actions to test the three SmallNewEngland cases using HiGHs after each PR
- [x] Base off of genx_as_submodule
- [x] Use Documentation.yml as a template

**Comment by Betristor** [comment]
@RuaridhMacd I write a runtest.jl using Test pkg to automatically run test scripts for us. But i can only manage to have it work locally after you activate local environment and type ```test``` in pkg management mode. To have this test work on github actions, I believe I need to figure out how to install highs solver on the machine that github will use when the action is triggered.
BTW, I checked GenX's runtests script, they just used some simple operations like addition which is invalid in testing. You could find new changes made to your branch on [```testDolphyn```](https://github.com/macroenergy/DOLPHYN/tree/testDolphyn) branch.
Anna's ThreeZones_Liquid case still fails in my situation. So I commented test script for her case. If it's functionable, test could be added at any time.
Sorry that I decided not to use Documentation.yml as example, I've found a test script dedicated for julia test called [```Run Julia package test```](https://github.com/marketplace/actions/run-julia-package-tests) created by julia-actions. The next step is to figure out how to install highs solver on the test environment.

**Comment by RuaridhMacd** [comment]
- [ ] @RuaridhMacd Take a look at the Gtihub Actions log files to diagnose error
- [ ] @Betristor Work out how to download and install HiGHs to a Github Actions machine

**Comment by Betristor** [comment]
@RuaridhMacd I believed that PR #156 has fulfilled things we required here. And I found that highs binary is not needed to perform the tests, at least in ubuntu machines.

**Comment by RuaridhMacd** [comment]
Resolved by #173
