### ISSUE TITLE
Output File Zone Value Incorrect

### ISSUE THREAD

**Issue by bennettm** [macroenergy/DOLPHYN#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After ran the Run.jl file from Example_Systems/SmallNewEngland/ThreeZones, I discovered that the file HSC_h2_pipeline_flow.csv has incorrect data for Zone.
<img width="986" alt="Screenshot 2023-10-10 at 2 54 26 PM" src="https://github.com/macroenergy/DOLPHYN/assets/2174909/f731378d-1a6c-4cc9-9db2-075ad957ac8a">
This is a bug and should be fixed.

### Expected Behavior

The value for Zone should be 1, 2, 3 these integers for the ThreeZones output file.

### Steps To Reproduce

1.  Follow the steps to run Example cases for DOLPHYN from readme.md
2. Choose Example_Systems/SmallNewEngland/ThreeZones/Run.jl to run
3. After step 2 runs successfully, open HSC_h2_pipeline_flow.csv from the Results_HSC folder and check the values for Zone.

### Environment

```markdown
- OS: MacBook Pro Ventura 13.6
- Julia version: 1.6.7
- Solver: Gurobi
- Solver version: 10.0.3
```

### Manifest.toml file

[Manifest.zip](https://github.com/macroenergy/DOLPHYN/files/12861100/Manifest.zip)

**Comment by RuaridhMacd** [comment]
Resolved by PR #186
