### ISSUE TITLE
Missing H2 transmission flows output file

### ISSUE THREAD

**Issue by dharik13** [macroenergy/DOLPHYN#22]
Similar to write_transmission_flows.jl for GenX, a script to generate H2 flows across various of zones of the model across the time steps would be useful.

**Comment by anna-nadia** [comment]
The output files HSC_h2_pipeline_flow and HSC_h2_pipeline_level have addressed this issue.

**Comment by Betristor** [comment]
@anna-nadia I wrote a *write_h2_transmission_flow.jl* to jointly recording the hydrogen flow of pipelines and trucks.
