### ISSUE TITLE
TDR not working in constant power and H2 load

### ISSUE THREAD

**Issue by Junwenlaw** [macroenergy/DOLPHYN#58]
I have noticed that TDR does not work well when the H2 load is a constant, and will generate an empty spreadsheet in the TDR folder. For a constant power load, TDR will not even run and produces an error of "ArgumentError: column name :Load_MW_z1 not found in the data frame".

**Comment by dharik13** [comment]
Test with Julia 1.7.3  - apparently this is not an issue when Julia version is changed to 1.7.3

**Comment by Junwenlaw** [comment]
Does not seem to be a problem with Julia version. If all columns (zones) of H2 load is constant then TDR would not work. Only need to have a slight variation in one of the time interval in one zone for the code to work.
