### ISSUE TITLE
Pipelines data file input does not include FOM

### ISSUE THREAD

**Issue by anna-nadia** [macroenergy/DOLPHYN#73]
The pipelines input file does not have a separate column for Fixed O&M (or Variable O&M). Since we currently don't have any pipelines, I added FOM as part of my CAPEX, but in the long term it might be good to have separate columns - so that we are consistent across our data inputs.

**Comment by Betristor** [comment]
Should we have FOM inputed as percentage of CAPEX? In other researches, fixed O&M costs are usually calculated as percentage of CAPEX.

**Comment by RuaridhMacd** [comment]
I think it would be best to stick with absolute costs / values, as that's what is used everywhere else.
Relative / percentage costs may be good to add in an updated user interface, but I think we should keep the 'real' inputs consistent.

**Comment by Betristor** [comment]
@RuaridhMacd Ok, to keep the inputs consistent is of importance in user experience. Using percentage for fom is for the convenience of research.
