### ISSUE TITLE
Proposal of a standard test example for code dev

### ISSUE THREAD

**Issue by Betristor** [macroenergy/DOLPHYN#74]
It's sometimes confusing to justify code quality in lack of a standard test example especially when new codes are introduced. 
In a system where couple effect like electricity and hydrogen and carbon is the point we care about, as later energy carriers and forms come in, it will be harder to distinguish whether our code could still keep logistic and correct. New couple joints could break everything down if it's wrong.
Could we have a tested and minimum example which will be verified to be correct on a specific point on development timeline so that we could trace back when code development seems wrong. And this example could be updated as code development moves on as milestones.

**Comment by Betristor** [comment]
@RuaridhMacd Mac, I was thinking what kind of example could be said to be a standard example. Today I'm debugging with my own code, it involves probably four or five positions that are different with previous code and upstream GenX. I need to fix these tiny differences on hand when emerging data, quite annoying but necessary. But still there will be some paramters that are missed during debuging. Then it came to my mind that the standard itself didn't exist for our code and examples. Like we can't extract a default settings from setting files, and we didn't have well-accepted load profiles as well as technical parameters. More importantly, we have no pattern in our codes, neither in the sub sectors nor in the overall structure. The standard itself should firstly be clarified.

**Comment by Betristor** [comment]
I'll close this issue and struggle to figure out a standard for code and example in later PR.

**Comment by RuaridhMacd** [comment]
@Betristor I think this is a long term issue which we can solve gradually. I have to finish some project work between now and the end of November, but would be happy to work together on a plan for after then.

**Comment by Betristor** [comment]
@RuaridhMacd Yeah, I agree to that. Temporarily I got some pieces of idea in mind but they are not gathered into a whole. It will take many teammates' work to get this done.

**Comment by Betristor** [comment]
This issue will be reopened if next version is on schedule. For the current version this is a stray.
