### ISSUE TITLE
Proposal of applying ModelScalingFactor in writing output part instead of in constraints and expressions

### ISSUE THREAD

**Issue by Betristor** [macroenergy/DOLPHYN#77]
In GenX, ModelScalingFactor is used to convert power unit from MW into GW which are both commonly used units in power system. But this conversion happens too many times in expressions and constraints. In code logic it's right but in development process it's annoying. A basic unit should be fixed at input stage and we could change it into many forms once the results are given.

**Comment by dharik13** [comment]
This is going to be considered in a future version
