### ISSUE TITLE
separate HSC_costs by technology

### ISSUE THREAD

**Issue by anna-nadia** [macroenergy/DOLPHYN#87]
Write now, HSC costs lumps everything together, including G2P. 
G2P needs to be separated, because it is not hydrogen generation but electrical generation. 
It would also be nicer to have costs for each sub-sector / technology. For example, separating hydrogen production from hydrogen storage.
Also, the NetworkExpansion costs still don't show up in each zone (only the Total shows up).

**Comment by anna-nadia** [comment]
I am looking at the new code, and it seems that variable costs for G2P are still lumped into the output "cH2Var". If we separate the fixed costs, then we need to separate the variables costs too, other it's not useful. 
Also the network expansion costs still don't show up for each zone, only the Total Value is there.

**Comment by dharik13** [comment]
@Junwenlaw  is this addressed?

**Comment by anna-nadia** [comment]
I have worked on this as part of adding liquefaction, and also adding the electricity costs associated with hydrogen production. Hopefully I can merge my branch at the end of this week.

**Comment by Junwenlaw** [comment]
Done, waiting for approval to merge edits
