### ISSUE TITLE
GenX Policies - Capacity Reserve Margin

### ISSUE THREAD

**Issue by chakz** [macroenergy/DOLPHYN#93]
The capacity reserve margin does not account for hydrogen storage and electrolyzer power consumption (flexible load). 

In the last update on the GenX policies for Capacity Reserve Margin, there was a term that accounted for asymmetric storage. This could be extended to account for hydrogen storage. However, this assumption needs to be validated. 

Additionally, the complete power balancing equation (that includes conversion and storage of hydrogen and electrolyzer power consumption) needs to be reviewed to ensure that all flexible loads and storage resources are accounted for in the balancing equation.

**Comment by dharik13** [comment]
@Junwenlaw please push the changes you made to CRM constraint for the XOM project so that we can close this issue. Please make sure to modify the documentation along with the code changes to push this issue and any changes in input files.

**Comment by RuaridhMacd** [comment]
- [ ] @Junwenlaw Push your changes / comment here so we know the status

**Comment by RuaridhMacd** [comment]
Resolved in #125
